services:
  app:
    build: .
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: DB_HOST
      DB_PORT: 5432
      DB_DATABASE: DB_DATABASE
      DB_USERNAME: DB_USERNAME
      DB_PASSWORD: DB_PASSWORD
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
    depends_on:
      - app